extends: airbnb-base
env:
  es6: true
  node: true
  mocha: true
rules:
  comma-dangle:
    - error
    - never
  linebreak-style: 0
  arrow-parens:
    - error
    - as-needed
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  no-console:
    - error
  quotes:
    - error
    - single
  # To allow ++ in for loop.
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-unused-expressions:
    - error
    - allowTernary: true
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
overrides: [
    {
        files: "*.test.js",
        rules: {
            "no-unused-expressions": "off"
        }
    }
]
